import { parseExpenses } from './parser.js';
const KEY='mis-gastos-v1';
const state=JSON.parse(localStorage.getItem(KEY)||'{"expenses":[],"cards":[],"categories":[]}');
let selectedDate=new Date(), editingId=null, reportRange='month', pending=[], discarded=null;
const $=s=>document.querySelector(s), money=(n,c)=>new Intl.NumberFormat('es-AR',{style:'currency',currency:c,maximumFractionDigits:2}).format(n||0);
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const sameDay=(a,b)=>new Date(a).toDateString()===new Date(b).toDateString();
function installmentExpenses(expense){
  if(expense.installments<=1)return [expense];
  return Array.from({length:expense.installments},(_,i)=>{const d=new Date(expense.date);d.setMonth(d.getMonth()+i);return {...expense,id:crypto.randomUUID(),parentId:expense.id,date:d.toISOString(),amount:expense.amount/expense.installments,installment:i+1};});
}
function render(){
  $('#todayLabel').textContent=selectedDate.toLocaleDateString('es-AR',{weekday:'long',day:'numeric',month:'long'});
  const day=state.expenses.filter(e=>sameDay(e.date,selectedDate));
  $('#arsTotal').textContent=money(day.filter(e=>e.currency==='ARS').reduce((s,e)=>s+e.amount,0),'ARS');
  $('#usdTotal').textContent=money(day.filter(e=>e.currency==='USD').reduce((s,e)=>s+e.amount,0),'USD');
  $('#expenseList').innerHTML=day.length?day.sort((a,b)=>b.date.localeCompare(a.date)).map(expenseHTML).join(''):'<div class="empty">Todavía no registraste gastos este día.</div>';
  detectUnusual(day); renderCards(); renderReport(); fillCardSelect();
}
function expenseHTML(e){const detail=[e.method,e.card,e.installments>1?`${e.installment||1}/${e.installments} cuotas`:null].filter(Boolean).join(' · ');return `<article class="expense" data-id="${e.id}"><div class="expense-icon">${e.method==='Efectivo'?'◆':e.method==='Crédito'?'▰':'●'}</div><div class="expense-info"><strong>${escape(e.concept)}</strong><span>${detail} · ${new Date(e.date).toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'})}</span></div><div class="amount">${money(e.amount,e.currency)}<small>${e.currency}</small></div></article>`}
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function detectUnusual(day){const past=state.expenses.filter(e=>!sameDay(e.date,new Date()));const avg=past.length?past.reduce((s,e)=>s+e.amount,0)/past.length:Infinity;$('#unusual').classList.toggle('hidden',!day.some(e=>e.amount>avg*2&&past.length>=5));}
function fillCardSelect(){const opts='<option value="">Ninguna</option>'+state.cards.map(c=>`<option>${escape(c.name)}</option>`).join('');$('#expenseCard').innerHTML=opts;}
function renderCards(){
  $('#cardList').innerHTML=state.cards.length?state.cards.map(c=>`<article class="card-item"><div class="top"><strong>${escape(c.name)}</strong><span>${c.type}</span></div><p>Cierra el ${c.closingDay} · Vence el ${c.dueDay} · Aviso ${c.reminderDays} días antes</p></article>`).join(''):'<div class="empty">No agregaste tarjetas todavía.</div>';
  $('#reminderList').innerHTML=state.cards.filter(c=>c.type==='Crédito').map(c=>{const total=state.expenses.filter(e=>e.card===c.name&&e.currency==='ARS').reduce((s,e)=>s+e.amount,0);return `<article class="reminder"><div><strong>${escape(c.name)}</strong><p class="muted">Vence el día ${c.dueDay}</p></div><strong>${money(total,'ARS')}</strong></article>`}).join('')||'<div class="empty">Los recordatorios aparecerán cuando agregues una tarjeta de crédito.</div>';
}
function renderReport(){let from,to=new Date();if(reportRange==='month'){from=new Date(to.getFullYear(),to.getMonth(),1);$('#reportTitle').textContent=to.toLocaleDateString('es-AR',{month:'long',year:'numeric'})}else if(reportRange==='year'){from=new Date(to.getFullYear(),0,1);$('#reportTitle').textContent=`Año ${to.getFullYear()}`}else{from=new Date($('#fromDate').value||'2000-01-01');to=new Date($('#toDate').value||'2100-01-01');$('#reportTitle').textContent='Rango personalizado'}const items=state.expenses.filter(e=>new Date(e.date)>=from&&new Date(e.date)<=new Date(to.getTime()+86400000));$('#reportArs').textContent=money(items.filter(e=>e.currency==='ARS').reduce((s,e)=>s+e.amount,0),'ARS');$('#reportUsd').textContent=money(items.filter(e=>e.currency==='USD').reduce((s,e)=>s+e.amount,0),'USD');const months=Array.from({length:12},(_,i)=>items.filter(e=>new Date(e.date).getMonth()===i&&e.currency==='ARS').reduce((s,e)=>s+e.amount,0));const max=Math.max(...months,1);$('#monthlyChart').innerHTML=months.map((v,i)=>`<div class="bar" style="height:${v/max*100}%" title="${money(v,'ARS')}"><span>${['E','F','M','A','M','J','J','A','S','O','N','D'][i]}</span></div>`).join('');}
function showToast(msg,undo=false){const t=$('#toast');t.textContent=msg;t.classList.add('show');t.onclick=undo?()=>{if(discarded){pending.splice(discarded.index,0,discarded.item);discarded=null;showPending();showToast('Gasto recuperado')}}:null;setTimeout(()=>t.classList.remove('show'),2500)}
function openExpense(data={}){editingId=data.id||null;$('#expenseDialogTitle').textContent=editingId?'Corregir gasto':'Nuevo gasto';$('#amount').value=data.amount||'';$('#concept').value=data.concept==='Sin concepto'?'':data.concept||'';$('#method').value=data.method||'Efectivo';$('#installments').value=data.installments||1;document.querySelector(`input[name=currency][value=${data.currency||'ARS'}]`).checked=true;fillCardSelect();$('#expenseCard').value=data.card||'';$('#expenseDialog').showModal();}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.view,nav button').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.view).classList.add('active');b.classList.add('active');render()});
document.querySelectorAll('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#manualBtn').onclick=()=>openExpense();$('#prevDay').onclick=()=>{selectedDate.setDate(selectedDate.getDate()-1);render()};$('#nextDay').onclick=()=>{selectedDate.setDate(selectedDate.getDate()+1);render()};
$('#expenseForm').onsubmit=e=>{e.preventDefault();const item={id:editingId||crypto.randomUUID(),amount:Number($('#amount').value),currency:document.querySelector('[name=currency]:checked').value,concept:$('#concept').value,category:$('#category').value,method:$('#method').value,card:$('#expenseCard').value,installments:Number($('#installments').value),date:editingId?(state.expenses.find(x=>x.id===editingId)?.date||new Date().toISOString()):new Date().toISOString(),source:'manual'};if(editingId)state.expenses=state.expenses.filter(x=>x.id!==editingId);state.expenses.push(...installmentExpenses(item));save();$('#expenseDialog').close();showToast('Gasto guardado');render()};
$('#addCard').onclick=()=>$('#cardDialog').showModal();$('#cardForm').onsubmit=e=>{e.preventDefault();state.cards.push({id:crypto.randomUUID(),name:$('#cardName').value,type:$('#cardType').value,closingDay:+$('#closingDay').value,dueDay:+$('#dueDay').value,reminderDays:+$('#reminderDays').value});save();e.target.reset();$('#cardDialog').close();showToast('Tarjeta agregada');render()};
document.querySelectorAll('.range-tabs button').forEach(b=>b.onclick=()=>{reportRange=b.dataset.range;document.querySelectorAll('.range-tabs button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('#customRange').classList.toggle('hidden',reportRange!=='custom');renderReport()});$('#fromDate').onchange=$('#toDate').onchange=renderReport;
$('#settingsBtn').onclick=()=>$('#settingsDialog').showModal();$('#biometricBtn').onclick=async()=>{if(!window.PublicKeyCredential)return showToast('Biometría no disponible en este dispositivo');showToast('Base biométrica lista; requiere un servidor seguro para activarse')};
function showPending(){if(!pending.length){if($('#confirmDialog').open)$('#confirmDialog').close();return}$('#pendingList').innerHTML=pending.map((e,i)=>`<article class="pending" data-i="${i}"><div class="pending-head"><div><strong>${escape(e.concept)}</strong><p class="muted">${e.method}${e.card?' · '+escape(e.card):''}${e.installments>1?' · '+e.installments+' cuotas':''}</p></div><strong>${e.amount?money(e.amount,e.currency):'Sin importe'}</strong></div><div class="actions"><button class="edit">Corregir</button><button class="confirm" ${!e.amount?'disabled':''}>✓ Confirmar</button></div></article>`).join('');if(!$('#confirmDialog').open)$('#confirmDialog').showModal();document.querySelectorAll('.pending').forEach(card=>{const i=+card.dataset.i;card.querySelector('.confirm').onclick=()=>confirmPending(i);card.querySelector('.edit').onclick=()=>{const item=pending.splice(i,1)[0];showPending();openExpense(item)};let start=0;card.ontouchstart=e=>start=e.touches[0].clientX;card.ontouchend=e=>{if(Math.abs(e.changedTouches[0].clientX-start)>80){discarded={item:pending.splice(i,1)[0],index:i};showPending();showToast('Descartado · Tocá para deshacer',true);}}});}
function confirmPending(i){const item=pending.splice(i,1)[0];state.expenses.push(...installmentExpenses(item));save();navigator.vibrate?.(80);try{const ctx=new AudioContext(),osc=ctx.createOscillator();osc.frequency.value=660;osc.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.09)}catch{}showToast('✓ Gasto confirmado');showPending();render()}
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;$('#micBtn').onclick=()=>{if(!SpeechRecognition){const phrase=prompt('Tu navegador no ofrece dictado. Escribí lo que dirías:');if(phrase){pending=parseExpenses(phrase,state.cards);showPending()}return}const r=new SpeechRecognition();r.lang='es-AR';r.interimResults=false;r.continuous=true;let text='';r.onstart=()=>{$('#micBtn').classList.add('listening');$('#voiceTitle').textContent='Escuchando…';$('#voiceHint').textContent='Tocá otra vez para terminar'};r.onresult=e=>{for(let i=e.resultIndex;i<e.results.length;i++)text+=' '+e.results[i][0].transcript};r.onend=()=>{$('#micBtn').classList.remove('listening');$('#voiceTitle').textContent='Tocá para hablar';$('#voiceHint').textContent='Podés decir varios gastos seguidos';if(text.trim()){pending=parseExpenses(text,state.cards);showPending()}};r.start()};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();
